#!/usr/bin/env python3
"""Exercise LJ, G1..G5 and converted n2p2 through LAMMPS CPU/GPU interfaces.

--fixtures is generated by write_target_fixtures from the Fortran test build.
Models are synthetic regression fixtures, not physical potentials.
"""
import argparse
from pathlib import Path
import shutil
import subprocess
import sys

p = argparse.ArgumentParser(description=__doc__)
p.add_argument('--lammps', required=True, type=Path)
p.add_argument('--fixtures', required=True, type=Path)
p.add_argument('--converter', required=True, type=Path)
p.add_argument('--output', required=True, type=Path)
p.add_argument('--ranks', nargs='+', type=int, default=[1, 2])
p.add_argument('--cases', nargs='+', default=['orthogonal', 'triclinic', 'empty'])
a = p.parse_args()
repo = Path(__file__).resolve().parents[4]
a.output = a.output.resolve()
a.output.mkdir(parents=True, exist_ok=True)
structure = '''CRYSTAL
PRIMVEC
5.6 0 0
0 5.8 0
0 0 6.0
PRIMCOORD
8 1
H 0.4 0.5 0.6
O 1.7 0.6 0.7
H 0.5 2.0 0.8
O 0.6 0.7 2.3
H 2.1 2.0 0.7
O 2.0 0.8 2.2
H 0.8 2.2 2.0
O 2.2 2.0 2.4
'''
for family in ['lj', 'behler', 'n2p2']:
    model = a.output / (family+'-model')
    model.mkdir(exist_ok=True)
    if family == 'n2p2':
        subprocess.run([str(a.converter.resolve()), 'n2p2-to-accelnet',
                        str(repo/'AccelNetPredictor/test/data/n2p2-virial-angular'), str(model)], check=True)
    else:
        for element in ['H', 'O']:
            shutil.copyfile(a.fixtures/f'{element}.{family}.nn.ascii', model/f'{element}.nn.ascii')
    (model/'structure0001.xsf').write_text(structure)
    subprocess.run([sys.executable, str(Path(__file__).with_name('check_gpu.py')),
                    '--lammps', str(a.lammps.resolve()), '--golden', str(model), '--elements', 'H', 'O',
                    '--output', str(a.output/family), '--ranks', *map(str, a.ranks), '--cases', *a.cases], check=True)
